[package]
name = "graph_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
petgraph = "0.6.2"
rand = "0.8.5"
thiserror = "1.0.37"
